### ISSUE TITLE
Create Link component

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#799]
## Todo:

- [x] Create React Component
- [x] Add story examples
- [x] Add test snapshots
