### ISSUE TITLE
Create EmptyDashboard component

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#801]
## Todo:

- [x] Create React Component
- [x] Add story examples
- [x] Add test snapshots

**Comment by daverau-optimizely** [comment]
Shipped in `27.1.0`
