### ISSUE TITLE
Scope flex and other helper classes for PreviewUI

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#848]
https://optimizely.atlassian.net/browse/WEB-2301

# Todo
- [x] Identify helper classes that need prefixing
- [x] Update PreviewUI HTML templates used in `optimizely` repo to use new prefixed helper classes
- [x] Update CSS in `proto` repo with duplicate rules so both old and new classes work; to be deleted in the future. The best approach here may be to duplicate all the helper files and rename them to optly-, search/replace to prefix the classes.
- [ ] Test locally via Chrome extension injection with the full Docker local setup
- [ ] Publish new CSS via github pages
- [x] Deploy via Optimizely and verify it all worked as expected
- [ ] Then delete the original helper files from Proto/Preview CSS bundle once we verity things are working after deploy

# List of classes to prefix with `optly-`

## Modification classes
```
soft-
push-
flush-
hard-
pointer-
weight--
cursor--
border--
float--
width--
display--
flex-
visibility-
```

## Plain classes
```
flex
micro
milli
muted
no-border
badge__
is-collapsed
is-active
token__text
drop-filter
```

## potentially an issue still
```
ui-draggable-handle
```

**Comment by daverau-optimizely** [comment]
https://optimizely.atlassian.net/browse/WEB-2301

**Comment by daverau-optimizely** [comment]
List of classes to prefix with `optly-`

## Modification classes
```
soft-
push-
flush-
hard-
flex-
pointer-
weight--
cursor--
border--
float--
width--
display--
```

## Plain classes
```
flex
micro
milli
muted
no-border
badge__
is-collapsed
ui-draggable-handle
token__text
drop-filter
```

**Comment by daverau-optimizely** [comment]
Done in the latest Preview UI migration to Optimizely.git
